# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: annotation_rst.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='annotation_rst.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x61nnotation_rst.proto\x1a\x19google/protobuf/any.proto\"\xb7\x01\n\rDiscourseUnit\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1c\n\x04left\x18\x02 \x01(\x0b\x32\x0e.DiscourseUnit\x12\x1d\n\x05right\x18\x03 \x01(\x0b\x32\x0e.DiscourseUnit\x12\x10\n\x08relation\x18\x04 \x01(\t\x12\x12\n\nnuclearity\x18\x05 \x01(\t\x12\r\n\x05proba\x18\x06 \x01(\t\x12\x0c\n\x04text\x18\x07 \x01(\t\x12\r\n\x05start\x18\x08 \x01(\x05\x12\x0b\n\x03\x65nd\x18\t \x01(\x05\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_DISCOURSEUNIT = _descriptor.Descriptor(
  name='DiscourseUnit',
  full_name='DiscourseUnit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DiscourseUnit.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='left', full_name='DiscourseUnit.left', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right', full_name='DiscourseUnit.right', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='relation', full_name='DiscourseUnit.relation', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nuclearity', full_name='DiscourseUnit.nuclearity', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proba', full_name='DiscourseUnit.proba', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='DiscourseUnit.text', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='DiscourseUnit.start', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='DiscourseUnit.end', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=235,
)

_DISCOURSEUNIT.fields_by_name['left'].message_type = _DISCOURSEUNIT
_DISCOURSEUNIT.fields_by_name['right'].message_type = _DISCOURSEUNIT
DESCRIPTOR.message_types_by_name['DiscourseUnit'] = _DISCOURSEUNIT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DiscourseUnit = _reflection.GeneratedProtocolMessageType('DiscourseUnit', (_message.Message,), {
  'DESCRIPTOR' : _DISCOURSEUNIT,
  '__module__' : 'annotation_rst_pb2'
  # @@protoc_insertion_point(class_scope:DiscourseUnit)
  })
_sym_db.RegisterMessage(DiscourseUnit)


# @@protoc_insertion_point(module_scope)
