# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: annotation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='annotation.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x61nnotation.proto\x1a\x19google/protobuf/any.proto\">\n\nAnnMapItem\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"*\n\rAnnotationMap\x12\x19\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0b.AnnMapItem\"4\n\x0e\x41nnotationList\x12\"\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x14.google.protobuf.Any\"0\n\x0f\x41nnotationTuple\x12\x1d\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x0f.AnnotationList\"\"\n\x04Span\x12\r\n\x05\x62\x65gin\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\".\n\nTaggedSpan\x12\x13\n\x04span\x18\x01 \x01(\x0b\x32\x05.Span\x12\x0b\n\x03tag\x18\x02 \x01(\t\"8\n\x0eTaggedRelation\x12\x0c\n\x04head\x18\x01 \x01(\x05\x12\x0b\n\x03\x64\x65p\x18\x02 \x01(\x05\x12\x0b\n\x03tag\x18\x03 \x01(\t\"*\n\x05Token\x12\x13\n\x04span\x18\x01 \x01(\x0b\x32\x05.Span\x12\x0c\n\x04text\x18\x02 \x01(\t\"&\n\x08Sentence\x12\r\n\x05\x62\x65gin\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\"\x1a\n\tLngString\x12\r\n\x05value\x18\x01 \x01(\t\"\x17\n\x06LngInt\x12\r\n\x05value\x18\x01 \x01(\x05\"-\n\x08WordSynt\x12\x0e\n\x06parent\x18\x01 \x01(\x05\x12\x11\n\tlink_name\x18\x02 \x01(\t\"X\n\x0eProcessRequest\x12\x15\n\rpipeline_name\x18\x01 \x01(\t\x12/\n\x11input_annotations\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"@\n\x0cProcessReply\x12\x30\n\x12output_annotations\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"2\n\x18RegisteredPipelinesReply\x12\x16\n\x0epipeline_names\x18\x01 \x03(\t\"\x06\n\x04Void\"F\n\x05\x45vent\x12\x1e\n\x04pred\x18\x01 \x01(\x0b\x32\x10.AnnotationTuple\x12\x1d\n\x04\x61rgs\x18\x02 \x01(\x0b\x32\x0f.AnnotationList2y\n\nNlpService\x12+\n\x07process\x12\x0f.ProcessRequest\x1a\r.ProcessReply\"\x00\x12>\n\x18get_registered_pipelines\x12\x05.Void\x1a\x19.RegisteredPipelinesReply\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_ANNMAPITEM = _descriptor.Descriptor(
  name='AnnMapItem',
  full_name='AnnMapItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='AnnMapItem.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='AnnMapItem.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=109,
)


_ANNOTATIONMAP = _descriptor.Descriptor(
  name='AnnotationMap',
  full_name='AnnotationMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='AnnotationMap.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=153,
)


_ANNOTATIONLIST = _descriptor.Descriptor(
  name='AnnotationList',
  full_name='AnnotationList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='AnnotationList.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=207,
)


_ANNOTATIONTUPLE = _descriptor.Descriptor(
  name='AnnotationTuple',
  full_name='AnnotationTuple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='AnnotationTuple.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=257,
)


_SPAN = _descriptor.Descriptor(
  name='Span',
  full_name='Span',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='begin', full_name='Span.begin', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='Span.end', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=293,
)


_TAGGEDSPAN = _descriptor.Descriptor(
  name='TaggedSpan',
  full_name='TaggedSpan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='span', full_name='TaggedSpan.span', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='TaggedSpan.tag', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=341,
)


_TAGGEDRELATION = _descriptor.Descriptor(
  name='TaggedRelation',
  full_name='TaggedRelation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='head', full_name='TaggedRelation.head', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dep', full_name='TaggedRelation.dep', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='TaggedRelation.tag', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=399,
)


_TOKEN = _descriptor.Descriptor(
  name='Token',
  full_name='Token',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='span', full_name='Token.span', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='Token.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=443,
)


_SENTENCE = _descriptor.Descriptor(
  name='Sentence',
  full_name='Sentence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='begin', full_name='Sentence.begin', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='Sentence.end', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=445,
  serialized_end=483,
)


_LNGSTRING = _descriptor.Descriptor(
  name='LngString',
  full_name='LngString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='LngString.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=485,
  serialized_end=511,
)


_LNGINT = _descriptor.Descriptor(
  name='LngInt',
  full_name='LngInt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='LngInt.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=513,
  serialized_end=536,
)


_WORDSYNT = _descriptor.Descriptor(
  name='WordSynt',
  full_name='WordSynt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='WordSynt.parent', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='link_name', full_name='WordSynt.link_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=538,
  serialized_end=583,
)


_PROCESSREQUEST = _descriptor.Descriptor(
  name='ProcessRequest',
  full_name='ProcessRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pipeline_name', full_name='ProcessRequest.pipeline_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_annotations', full_name='ProcessRequest.input_annotations', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=585,
  serialized_end=673,
)


_PROCESSREPLY = _descriptor.Descriptor(
  name='ProcessReply',
  full_name='ProcessReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='output_annotations', full_name='ProcessReply.output_annotations', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=675,
  serialized_end=739,
)


_REGISTEREDPIPELINESREPLY = _descriptor.Descriptor(
  name='RegisteredPipelinesReply',
  full_name='RegisteredPipelinesReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pipeline_names', full_name='RegisteredPipelinesReply.pipeline_names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=741,
  serialized_end=791,
)


_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=793,
  serialized_end=799,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pred', full_name='Event.pred', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='Event.args', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=801,
  serialized_end=871,
)

_ANNMAPITEM.fields_by_name['value'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_ANNOTATIONMAP.fields_by_name['data'].message_type = _ANNMAPITEM
_ANNOTATIONLIST.fields_by_name['data'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_ANNOTATIONTUPLE.fields_by_name['data'].message_type = _ANNOTATIONLIST
_TAGGEDSPAN.fields_by_name['span'].message_type = _SPAN
_TOKEN.fields_by_name['span'].message_type = _SPAN
_PROCESSREQUEST.fields_by_name['input_annotations'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_PROCESSREPLY.fields_by_name['output_annotations'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_EVENT.fields_by_name['pred'].message_type = _ANNOTATIONTUPLE
_EVENT.fields_by_name['args'].message_type = _ANNOTATIONLIST
DESCRIPTOR.message_types_by_name['AnnMapItem'] = _ANNMAPITEM
DESCRIPTOR.message_types_by_name['AnnotationMap'] = _ANNOTATIONMAP
DESCRIPTOR.message_types_by_name['AnnotationList'] = _ANNOTATIONLIST
DESCRIPTOR.message_types_by_name['AnnotationTuple'] = _ANNOTATIONTUPLE
DESCRIPTOR.message_types_by_name['Span'] = _SPAN
DESCRIPTOR.message_types_by_name['TaggedSpan'] = _TAGGEDSPAN
DESCRIPTOR.message_types_by_name['TaggedRelation'] = _TAGGEDRELATION
DESCRIPTOR.message_types_by_name['Token'] = _TOKEN
DESCRIPTOR.message_types_by_name['Sentence'] = _SENTENCE
DESCRIPTOR.message_types_by_name['LngString'] = _LNGSTRING
DESCRIPTOR.message_types_by_name['LngInt'] = _LNGINT
DESCRIPTOR.message_types_by_name['WordSynt'] = _WORDSYNT
DESCRIPTOR.message_types_by_name['ProcessRequest'] = _PROCESSREQUEST
DESCRIPTOR.message_types_by_name['ProcessReply'] = _PROCESSREPLY
DESCRIPTOR.message_types_by_name['RegisteredPipelinesReply'] = _REGISTEREDPIPELINESREPLY
DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnnMapItem = _reflection.GeneratedProtocolMessageType('AnnMapItem', (_message.Message,), dict(
  DESCRIPTOR = _ANNMAPITEM,
  __module__ = 'annotation_pb2'
  # @@protoc_insertion_point(class_scope:AnnMapItem)
  ))
_sym_db.RegisterMessage(AnnMapItem)

AnnotationMap = _reflection.GeneratedProtocolMessageType('AnnotationMap', (_message.Message,), dict(
  DESCRIPTOR = _ANNOTATIONMAP,
  __module__ = 'annotation_pb2'
  # @@protoc_insertion_point(class_scope:AnnotationMap)
  ))
_sym_db.RegisterMessage(AnnotationMap)

AnnotationList = _reflection.GeneratedProtocolMessageType('AnnotationList', (_message.Message,), dict(
  DESCRIPTOR = _ANNOTATIONLIST,
  __module__ = 'annotation_pb2'
  # @@protoc_insertion_point(class_scope:AnnotationList)
  ))
_sym_db.RegisterMessage(AnnotationList)

AnnotationTuple = _reflection.GeneratedProtocolMessageType('AnnotationTuple', (_message.Message,), dict(
  DESCRIPTOR = _ANNOTATIONTUPLE,
  __module__ = 'annotation_pb2'
  # @@protoc_insertion_point(class_scope:AnnotationTuple)
  ))
_sym_db.RegisterMessage(AnnotationTuple)

Span = _reflection.GeneratedProtocolMessageType('Span', (_message.Message,), dict(
  DESCRIPTOR = _SPAN,
  __module__ = 'annotation_pb2'
  # @@protoc_insertion_point(class_scope:Span)
  ))
_sym_db.RegisterMessage(Span)

TaggedSpan = _reflection.GeneratedProtocolMessageType('TaggedSpan', (_message.Message,), dict(
  DESCRIPTOR = _TAGGEDSPAN,
  __module__ = 'annotation_pb2'
  # @@protoc_insertion_point(class_scope:TaggedSpan)
  ))
_sym_db.RegisterMessage(TaggedSpan)

TaggedRelation = _reflection.GeneratedProtocolMessageType('TaggedRelation', (_message.Message,), dict(
  DESCRIPTOR = _TAGGEDRELATION,
  __module__ = 'annotation_pb2'
  # @@protoc_insertion_point(class_scope:TaggedRelation)
  ))
_sym_db.RegisterMessage(TaggedRelation)

Token = _reflection.GeneratedProtocolMessageType('Token', (_message.Message,), dict(
  DESCRIPTOR = _TOKEN,
  __module__ = 'annotation_pb2'
  # @@protoc_insertion_point(class_scope:Token)
  ))
_sym_db.RegisterMessage(Token)

Sentence = _reflection.GeneratedProtocolMessageType('Sentence', (_message.Message,), dict(
  DESCRIPTOR = _SENTENCE,
  __module__ = 'annotation_pb2'
  # @@protoc_insertion_point(class_scope:Sentence)
  ))
_sym_db.RegisterMessage(Sentence)

LngString = _reflection.GeneratedProtocolMessageType('LngString', (_message.Message,), dict(
  DESCRIPTOR = _LNGSTRING,
  __module__ = 'annotation_pb2'
  # @@protoc_insertion_point(class_scope:LngString)
  ))
_sym_db.RegisterMessage(LngString)

LngInt = _reflection.GeneratedProtocolMessageType('LngInt', (_message.Message,), dict(
  DESCRIPTOR = _LNGINT,
  __module__ = 'annotation_pb2'
  # @@protoc_insertion_point(class_scope:LngInt)
  ))
_sym_db.RegisterMessage(LngInt)

WordSynt = _reflection.GeneratedProtocolMessageType('WordSynt', (_message.Message,), dict(
  DESCRIPTOR = _WORDSYNT,
  __module__ = 'annotation_pb2'
  # @@protoc_insertion_point(class_scope:WordSynt)
  ))
_sym_db.RegisterMessage(WordSynt)

ProcessRequest = _reflection.GeneratedProtocolMessageType('ProcessRequest', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSREQUEST,
  __module__ = 'annotation_pb2'
  # @@protoc_insertion_point(class_scope:ProcessRequest)
  ))
_sym_db.RegisterMessage(ProcessRequest)

ProcessReply = _reflection.GeneratedProtocolMessageType('ProcessReply', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSREPLY,
  __module__ = 'annotation_pb2'
  # @@protoc_insertion_point(class_scope:ProcessReply)
  ))
_sym_db.RegisterMessage(ProcessReply)

RegisteredPipelinesReply = _reflection.GeneratedProtocolMessageType('RegisteredPipelinesReply', (_message.Message,), dict(
  DESCRIPTOR = _REGISTEREDPIPELINESREPLY,
  __module__ = 'annotation_pb2'
  # @@protoc_insertion_point(class_scope:RegisteredPipelinesReply)
  ))
_sym_db.RegisterMessage(RegisteredPipelinesReply)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'annotation_pb2'
  # @@protoc_insertion_point(class_scope:Void)
  ))
_sym_db.RegisterMessage(Void)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'annotation_pb2'
  # @@protoc_insertion_point(class_scope:Event)
  ))
_sym_db.RegisterMessage(Event)



_NLPSERVICE = _descriptor.ServiceDescriptor(
  name='NlpService',
  full_name='NlpService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=873,
  serialized_end=994,
  methods=[
  _descriptor.MethodDescriptor(
    name='process',
    full_name='NlpService.process',
    index=0,
    containing_service=None,
    input_type=_PROCESSREQUEST,
    output_type=_PROCESSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_registered_pipelines',
    full_name='NlpService.get_registered_pipelines',
    index=1,
    containing_service=None,
    input_type=_VOID,
    output_type=_REGISTEREDPIPELINESREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NLPSERVICE)

DESCRIPTOR.services_by_name['NlpService'] = _NLPSERVICE

# @@protoc_insertion_point(module_scope)
